<!DOCTYPE html>
<!-- saved from url=(0048)http://csc174.org/midterm/midris2/newsletter.php -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Espressos | Newsletter</title>
	<meta name="viewport" content="width=device-width, initial scale=1.0">
	<link href="css/styles.css" rel="stylesheet">
</head>

<body class="container" style="">
	<div class="row">
		<header class="column"><a href="index.php">
			<h1>Explaining Espressos</h1>
			<span class="byline">For UR coffee shop patrons wondering how their drinks are made...</span></a>
		</header>

		<aside>To learn how to <strong>save money</strong> on coffee: <a href="newsletter.php" class="button">sign up for the newsletter!</a></aside>
	</div>